name: Deploy DocC to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v6
      - name: Setup Xcode
        run: xcodes select
      - name: Build DocC
        run: |
          mkdir -p ./docs
          swift package \
            --allow-writing-to-directory ./docs \
            generate-documentation \
            --enable-experimental-combined-documentation \
            --target Camera \
            --target HeadphoneMotion \
            --target ImageClassification \
            --output-path ./docs \
            --disable-indexing \
            --transform-for-static-hosting \
            --hosting-base-path kantacky-kit
      - uses: actions/upload-artifact@v7
        id: docs
        with:
          path: docs

  deploy:
    needs: build
    runs-on: macos-26
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: docs
        uses: actions/deploy-pages@v4
